name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "19780204.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.19780204.xyz", custom_domain = true },
#   { pattern = "quay.19780204.xyz", custom_domain = true },
#   { pattern = "gcr.19780204.xyz", custom_domain = true },
#   { pattern = "k8s-gcr.19780204.xyz", custom_domain = true },
#   { pattern = "k8s.19780204.xyz", custom_domain = true },
#   { pattern = "ghcr.19780204.xyz", custom_domain = true },
#   { pattern = "cloudsmith.19780204.xyz", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
